# Generated by Django 5.2.1 on 2025-09-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='review',
            name='sentiment',
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='review',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
