# Generated by Django 5.2.6 on 2025-09-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_review_sentiment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='category',
            field=models.CharField(choices=[('product', 'Product Quality/Features'), ('delivery', 'Packaging/Delivery'), ('seller', 'Seller/Service'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='sentiment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
