# Generated by Django 5.2.6 on 2025-09-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_criticalissue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criticalissue',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='criticalissue',
            name='issue_text',
        ),
        migrations.RemoveField(
            model_name='criticalissue',
            name='severity',
        ),
        migrations.AddField(
            model_name='criticalissue',
            name='avg_sentiment_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='criticalissue',
            name='phrase',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='criticalissue',
            name='frequency',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
