# Generated by Django 5.2.6 on 2025-09-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_criticalissue_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criticalissue',
            name='aspect',
            field=models.CharField(default='general', max_length=50),
        ),
    ]
