# Generated by Django 5.2.6 on 2025-09-06 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_review_is_critical_delete_criticalissue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_critical',
        ),
        migrations.CreateModel(
            name='CriticalIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(blank=True, max_length=255, null=True)),
                ('frequency', models.PositiveIntegerField(default=0)),
                ('avg_sentiment_score', models.FloatField(default=0.0)),
                ('aspect', models.CharField(default='general', max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
    ]
