# Generated by Django 5.2.6 on 2025-09-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_review_is_critical_criticalissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_critical',
            field=models.BooleanField(default=False),
        ),
    ]
