# Generated by Django 5.2.6 on 2025-09-07 00:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_review_is_critical'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pid',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
