# Generated by Django 5.2.6 on 2025-09-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_product_created_at_remove_product_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
