# Generated by Django 5.2.6 on 2025-09-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
